// <auto-generated />
using System;
using ExpMedia.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpMedia.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220706080610_hni")]
    partial class hni
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExpMedia.Domain.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelectedPost")
                        .HasColumnType("bit");

                    b.Property<bool>("OnlyMe")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityUserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("ExpMedia.Domain.ActivityAttendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityCreatedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRequest")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityAttendees");
                });

            modelBuilder.Entity("ExpMedia.Domain.ActivityNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotifyFromId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NotifyToId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("NotifyFromId");

                    b.HasIndex("NotifyToId");

                    b.ToTable("ActivityNotifications");
                });

            modelBuilder.Entity("ExpMedia.Domain.ActivityUserSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("UsersId");

                    b.ToTable("ActivityUserSelections");
                });

            modelBuilder.Entity("ExpMedia.Domain.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ExpMedia.Domain.BlockUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BlockCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserToBlockId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserWhoBlockId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserToBlockId");

                    b.HasIndex("UserWhoBlockId");

                    b.ToTable("BlockUsersx");
                });

            modelBuilder.Entity("ExpMedia.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("ActivityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ActivityUserId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ExpMedia.Domain.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentCreatedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateReact")
                        .HasColumnType("datetime2");

                    b.Property<int>("Heart")
                        .HasColumnType("int");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<int>("Unlike")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommentCreatedUserId");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");
                });

            modelBuilder.Entity("ExpMedia.Domain.MessageTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MessageById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MessageToUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MessageById");

                    b.HasIndex("MessageToUserId");

                    b.ToTable("MessageTables");
                });

            modelBuilder.Entity("ExpMedia.Domain.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MessageById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("MessageCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MessageTableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageById");

                    b.HasIndex("MessageTableId");

                    b.ToTable("Messagesx");
                });

            modelBuilder.Entity("ExpMedia.Domain.MessagesGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GroupCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserMadeById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserMadeById");

                    b.ToTable("MessagesGroups");
                });

            modelBuilder.Entity("ExpMedia.Domain.SharingActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateShared")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OnlyMe")
                        .HasColumnType("bit");

                    b.Property<string>("SharedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("SharedUserId");

                    b.ToTable("SharingActivities");
                });

            modelBuilder.Entity("ExpMedia.Domain.SubMessageGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MessageToUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MessagesGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageToUserId");

                    b.HasIndex("MessagesGroupId");

                    b.ToTable("SubMessageGroups");
                });

            modelBuilder.Entity("ExpMedia.Domain.SubUserMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MessageCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubMessageGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubMessageGroupId");

                    b.ToTable("SubUserMessages");
                });

            modelBuilder.Entity("ExpMedia.Domain.TagUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserToTagId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserWhoTaggedId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserToTagId");

                    b.HasIndex("UserWhoTaggedId");

                    b.ToTable("TagUsers");
                });

            modelBuilder.Entity("ExpMedia.Domain.UserFollowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<string>("UserToFollowId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserWhoFollowedId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserToFollowId");

                    b.HasIndex("UserWhoFollowedId");

                    b.ToTable("UserFollowings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ExpMedia.Domain.Activity", b =>
                {
                    b.HasOne("ExpMedia.Domain.AppUser", "ActivityUser")
                        .WithMany("ActivityUsers")
                        .HasForeignKey("ActivityUserId");

                    b.Navigation("ActivityUser");
                });

            modelBuilder.Entity("ExpMedia.Domain.ActivityAttendee", b =>
                {
                    b.HasOne("ExpMedia.Domain.Activity", "Activity")
                        .WithMany("Attendees")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpMedia.Domain.AppUser", "User")
                        .WithMany("Activitie")
                        .HasForeignKey("UserId");

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpMedia.Domain.ActivityNotification", b =>
                {
                    b.HasOne("ExpMedia.Domain.Activity", "Activity")
                        .WithMany("ActivityNotifications")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpMedia.Domain.AppUser", "NotifyFrom")
                        .WithMany()
                        .HasForeignKey("NotifyFromId");

                    b.HasOne("ExpMedia.Domain.AppUser", "NotifyTo")
                        .WithMany("NotifyToUser")
                        .HasForeignKey("NotifyToId");

                    b.Navigation("Activity");

                    b.Navigation("NotifyFrom");

                    b.Navigation("NotifyTo");
                });

            modelBuilder.Entity("ExpMedia.Domain.ActivityUserSelection", b =>
                {
                    b.HasOne("ExpMedia.Domain.Activity", "Activity")
                        .WithMany("ActivityUserSelections")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpMedia.Domain.AppUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("ExpMedia.Domain.AppUser", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId");

                    b.Navigation("Activity");

                    b.Navigation("CreatedUser");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ExpMedia.Domain.BlockUsers", b =>
                {
                    b.HasOne("ExpMedia.Domain.AppUser", "UserToBlock")
                        .WithMany("ListOfToBlockUser")
                        .HasForeignKey("UserToBlockId");

                    b.HasOne("ExpMedia.Domain.AppUser", "UserWhoBlock")
                        .WithMany()
                        .HasForeignKey("UserWhoBlockId");

                    b.Navigation("UserToBlock");

                    b.Navigation("UserWhoBlock");
                });

            modelBuilder.Entity("ExpMedia.Domain.Comment", b =>
                {
                    b.HasOne("ExpMedia.Domain.Activity", "Activity")
                        .WithMany("Comments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpMedia.Domain.AppUser", "ActivityUser")
                        .WithMany()
                        .HasForeignKey("ActivityUserId");

                    b.HasOne("ExpMedia.Domain.AppUser", "Author")
                        .WithMany("AuthorUsers")
                        .HasForeignKey("AuthorId");

                    b.Navigation("Activity");

                    b.Navigation("ActivityUser");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ExpMedia.Domain.CommentReaction", b =>
                {
                    b.HasOne("ExpMedia.Domain.AppUser", "CommentCreatedUser")
                        .WithMany("CommentUser")
                        .HasForeignKey("CommentCreatedUserId");

                    b.HasOne("ExpMedia.Domain.Comment", "Comment")
                        .WithMany("CommentReactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpMedia.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Comment");

                    b.Navigation("CommentCreatedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpMedia.Domain.MessageTable", b =>
                {
                    b.HasOne("ExpMedia.Domain.AppUser", "MessageBy")
                        .WithMany()
                        .HasForeignKey("MessageById");

                    b.HasOne("ExpMedia.Domain.AppUser", "MessageToUser")
                        .WithMany()
                        .HasForeignKey("MessageToUserId");

                    b.Navigation("MessageBy");

                    b.Navigation("MessageToUser");
                });

            modelBuilder.Entity("ExpMedia.Domain.Messages", b =>
                {
                    b.HasOne("ExpMedia.Domain.AppUser", "MessageBy")
                        .WithMany()
                        .HasForeignKey("MessageById");

                    b.HasOne("ExpMedia.Domain.MessageTable", "MessageTable")
                        .WithMany("Messagesx")
                        .HasForeignKey("MessageTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageBy");

                    b.Navigation("MessageTable");
                });

            modelBuilder.Entity("ExpMedia.Domain.MessagesGroup", b =>
                {
                    b.HasOne("ExpMedia.Domain.AppUser", "UserMadeBy")
                        .WithMany()
                        .HasForeignKey("UserMadeById");

                    b.Navigation("UserMadeBy");
                });

            modelBuilder.Entity("ExpMedia.Domain.SharingActivity", b =>
                {
                    b.HasOne("ExpMedia.Domain.Activity", "Activity")
                        .WithMany("SharingActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpMedia.Domain.AppUser", "SharedUser")
                        .WithMany("SharingActivitiesUsers")
                        .HasForeignKey("SharedUserId");

                    b.Navigation("Activity");

                    b.Navigation("SharedUser");
                });

            modelBuilder.Entity("ExpMedia.Domain.SubMessageGroup", b =>
                {
                    b.HasOne("ExpMedia.Domain.AppUser", "MessageToUser")
                        .WithMany()
                        .HasForeignKey("MessageToUserId");

                    b.HasOne("ExpMedia.Domain.MessagesGroup", "MessagesGroup")
                        .WithMany("SubMessageGroups")
                        .HasForeignKey("MessagesGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessagesGroup");

                    b.Navigation("MessageToUser");
                });

            modelBuilder.Entity("ExpMedia.Domain.SubUserMessages", b =>
                {
                    b.HasOne("ExpMedia.Domain.SubMessageGroup", "MessagesGroup")
                        .WithMany("SubUserMessagesx")
                        .HasForeignKey("SubMessageGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessagesGroup");
                });

            modelBuilder.Entity("ExpMedia.Domain.TagUser", b =>
                {
                    b.HasOne("ExpMedia.Domain.Activity", "Activity")
                        .WithMany("TagUsers")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpMedia.Domain.AppUser", "UserToTag")
                        .WithMany("UsersTagged")
                        .HasForeignKey("UserToTagId");

                    b.HasOne("ExpMedia.Domain.AppUser", "UserWhoTagged")
                        .WithMany()
                        .HasForeignKey("UserWhoTaggedId");

                    b.Navigation("Activity");

                    b.Navigation("UserToTag");

                    b.Navigation("UserWhoTagged");
                });

            modelBuilder.Entity("ExpMedia.Domain.UserFollowing", b =>
                {
                    b.HasOne("ExpMedia.Domain.AppUser", "UserToFollow")
                        .WithMany("Followings")
                        .HasForeignKey("UserToFollowId");

                    b.HasOne("ExpMedia.Domain.AppUser", "UserWhoFollowed")
                        .WithMany()
                        .HasForeignKey("UserWhoFollowedId");

                    b.Navigation("UserToFollow");

                    b.Navigation("UserWhoFollowed");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ExpMedia.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ExpMedia.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpMedia.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ExpMedia.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpMedia.Domain.Activity", b =>
                {
                    b.Navigation("ActivityNotifications");

                    b.Navigation("ActivityUserSelections");

                    b.Navigation("Attendees");

                    b.Navigation("Comments");

                    b.Navigation("SharingActivities");

                    b.Navigation("TagUsers");
                });

            modelBuilder.Entity("ExpMedia.Domain.AppUser", b =>
                {
                    b.Navigation("Activitie");

                    b.Navigation("ActivityUsers");

                    b.Navigation("AuthorUsers");

                    b.Navigation("CommentUser");

                    b.Navigation("Followings");

                    b.Navigation("ListOfToBlockUser");

                    b.Navigation("NotifyToUser");

                    b.Navigation("SharingActivitiesUsers");

                    b.Navigation("UsersTagged");
                });

            modelBuilder.Entity("ExpMedia.Domain.Comment", b =>
                {
                    b.Navigation("CommentReactions");
                });

            modelBuilder.Entity("ExpMedia.Domain.MessageTable", b =>
                {
                    b.Navigation("Messagesx");
                });

            modelBuilder.Entity("ExpMedia.Domain.MessagesGroup", b =>
                {
                    b.Navigation("SubMessageGroups");
                });

            modelBuilder.Entity("ExpMedia.Domain.SubMessageGroup", b =>
                {
                    b.Navigation("SubUserMessagesx");
                });
#pragma warning restore 612, 618
        }
    }
}
